//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameResultService_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameResultService_1
    {
        public long ID { get; set; }
        public long win { get; set; }
        public System.DateTime timestamp { get; set; }
        public long playerId { get; set; }
        public long gameId { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
    }
}
