//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameResultService_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.GameResultService_1 = new HashSet<GameResultService_1>();
        }
    
        public long Id { get; set; }
        public string NamePlayer { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<GameResultService_1> GameResultService_1 { get; set; }
    }
}
