//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoWCF.GameOperationServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GameOperationServiceReference.IGameOperationService")]
    public interface IGameOperationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameOperationService/InserirResultado", ReplyAction="http://tempuri.org/IGameOperationService/InserirResultadoResponse")]
        void InserirResultado(long playerId, long gameID, long win);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameOperationService/InserirResultado", ReplyAction="http://tempuri.org/IGameOperationService/InserirResultadoResponse")]
        System.Threading.Tasks.Task InserirResultadoAsync(long playerId, long gameID, long win);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameOperationServiceChannel : ServicoWCF.GameOperationServiceReference.IGameOperationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameOperationServiceClient : System.ServiceModel.ClientBase<ServicoWCF.GameOperationServiceReference.IGameOperationService>, ServicoWCF.GameOperationServiceReference.IGameOperationService {
        
        public GameOperationServiceClient() {
        }
        
        public GameOperationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameOperationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameOperationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameOperationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InserirResultado(long playerId, long gameID, long win) {
            base.Channel.InserirResultado(playerId, gameID, win);
        }
        
        public System.Threading.Tasks.Task InserirResultadoAsync(long playerId, long gameID, long win) {
            return base.Channel.InserirResultadoAsync(playerId, gameID, win);
        }
    }
}
